name: Publish gh pages

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: |
        bundle install
    - name: Generate site
      run: |
        bundle exec jekyll build 
    - name: List generated files
      run: |
        echo $PWD
        ls _site
