name: Publish gh pages

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
      
    - name: Install Jekyll and bundler
      run: |
        gem install jekyll bundler
    - name: DEBUG
      run: |
        echo $PWD;
        echo ls
    - name: Generate site
      run: |
        bundler exec jekyll build 
        
